<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Referenced from the SPARC Architecture Manual, Version 8: http://sparc.org/standards/V8.pdf</string>
	<key>fileTypes</key>
	<array>
		<string>m</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>SPARC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>!</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sparc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SPARC comments</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.sparc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double quote strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.sparc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single quote strings</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.sparc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>comment</key>
			<string>M4 macro definitions. Should these even be here?</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.interpolated.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Regular opcodes</string>
			<key>match</key>
			<string>\b(?i)(cmp|tst|restore|save|set|not|neg|inc|dec|deccc|bst|bset|bclr|btog|clr|clrb|clrh|mov|ldsb|ldsh|ldub|lduh|ld|ldd|ldsba|ldsha|lduba|lduha|lda|ldda|ldf|lddf|ldfsr|ldc|lddc|ldcsr|stb|sth|st|std|stba|stha|sta|stda|stf|stdf|stfsr|stdfq|ldstub|ldstuba|swap|swapa|sethi|and|andcc|andn|andncc|or|orcc|orn|orncc|xor|xorcc|xnor|xnorcc|sll|srl|sra|add|addcc|addx|addxcc|taddcc|taddcctv|sub|subcc|subx|subxcc|tsubcc|tsubcctv|mulscc|umul|umulcc|smul|smulcc|udiv|udivcc|sdiv|sdivcc|bicc|fbfcc|cbccc|rett|ticc|rdasr|rdy|rdpsr|rdwim|rdtbr|wrasr|wry|wrpsr|wrwim|wrtbr|stbar|unimp|flush|fpop|cpop)(?-i)\b</string>
			<key>name</key>
			<string>keyword.control.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Opcodes that require delay slots</string>
			<key>match</key>
			<string>\b(?i)(ba|bn|bne|be|bg|ble|bge|bl|bgu|bleu|bcc|bcs|bpos|bneg|bvc|bvs|ret|retl|call|jmp|jmpl|return|b)(?-i)\b</string>
			<key>name</key>
			<string>constant.other.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>No operation, for delay slots</string>
			<key>match</key>
			<string>\b(nop)\b</string>
			<key>name</key>
			<string>support.constant.variable.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Basic number operators</string>
			<key>match</key>
			<string>(&amp;|-|\+|\||\[|\]|,)</string>
			<key>name</key>
			<string>keyword.operator.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Special registers &amp; register-like entities</string>
			<key>match</key>
			<string>(%)(sp|fp|hi|lo)</string>
			<key>name</key>
			<string>support.variable.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Regular registers</string>
			<key>match</key>
			<string>(%)(((i|o|g|l)[0-7]))|((%)r([0-9]|[1-2][0-9]|3[0-2])\b)</string>
			<key>name</key>
			<string>variable.language.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>User-defined registers (e.g. from macros)</string>
			<key>match</key>
			<string>(%)\w+</string>
			<key>name</key>
			<string>variable.other.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels</string>
			<key>match</key>
			<string>[\S]+:</string>
			<key>name</key>
			<string>entity.name.function.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pseudo-operators</string>
			<key>match</key>
			<string>\.(ascii|asciz|text|data|bss|skip|align|byte|half|word|single|double|quad|global|common|empty|file|section|type|proc|size|ident|section)\b</string>
			<key>name</key>
			<string>storage.modifier.sparc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Macro definitions</string>
			<key>match</key>
			<string>define</string>
			<key>name</key>
			<string>support.function.sparc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sparc</string>
	<key>uuid</key>
	<string>d407d941-d4c9-4203-8445-9a64b75a996a</string>
</dict>
</plist>
